import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";

const fontSans = Noto_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
});

const fontSerif = Noto_Sans({
  subsets: ["latin"],
  variable: "--font-serif",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontSans.variable} ${fontSerif.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}